# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KingdomOfCurling' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'Alamofire', '~> 4.7'
  # Pods for KingdomOfCurling

  target 'KingdomOfCurlingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KingdomOfCurlingUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
